PlantBuddy/Pages/PlantPictures/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.PlantPictures
{
    public class CreateModel : PageModel
    {
        private readonly PlantBuddyContext _context;
        private IWebHostEnvironment _environment;

        public CreateModel(PlantBuddyContext context, IWebHostEnvironment environment)
        {
            _context = context;
            _environment = environment;
        }

        public IActionResult OnGet()
        {
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "PlantName");
            return Page();
        }

        [BindProperty]
        public IFormFile PictureUpload { get; set; }

        [BindProperty]
        public PlantPicture PlantPicture { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (_context.PlantPictures == null || PlantPicture == null) //!ModelState.IsValid
            {
                return Page();
            }

            var x = PlantPicture.Picture;

            // REF: https://www.youtube.com/watch?v=Du8brcxA-KM
            using (BinaryReader br = new BinaryReader(PictureUpload.OpenReadStream()))
            {
                PlantPicture.Picture = br.ReadBytes((int)PictureUpload.Length);
            }

            _context.PlantPictures.Add(PlantPicture);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PlantBuddy/Pages/PlantPictures/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.PlantPictures
{
    public class DeleteModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public DeleteModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        [BindProperty]
      public PlantPicture PlantPicture { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.PlantPictures == null)
            {
                return NotFound();
            }

            var plantpicture = await _context.PlantPictures.FirstOrDefaultAsync(m => m.PlantPictureId == id);

            if (plantpicture == null)
            {
                return NotFound();
            }
            else 
            {
                PlantPicture = plantpicture;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.PlantPictures == null)
            {
                return NotFound();
            }
            var plantpicture = await _context.PlantPictures.FindAsync(id);

            if (plantpicture != null)
            {
                PlantPicture = plantpicture;
                _context.PlantPictures.Remove(PlantPicture);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PlantBuddy/Pages/PlantPictures/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.PlantPictures
{
    public class DetailsModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public DetailsModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

      public PlantPicture PlantPicture { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.PlantPictures == null)
            {
                return NotFound();
            }

            var plantpicture = await _context.PlantPictures.FirstOrDefaultAsync(m => m.PlantPictureId == id);
            if (plantpicture == null)
            {
                return NotFound();
            }
            else 
            {
                PlantPicture = plantpicture;
            }
            return Page();
        }
    }
}

PlantBuddy/Pages/PlantPictures/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.PlantPictures
{
    public class EditModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public EditModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        [BindProperty]
        public PlantPicture PlantPicture { get; set; } = default!;

        public string Image { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.PlantPictures == null)
            {
                return NotFound();
            }

            // REF: https://www.c-sharpcorner.com/article/mvc-display-image-from-byte-array/
            byte[] picture = _context.PlantPictures.Find(id).Picture;
            string imgDataURL = PlantPicture.ConvertImage(picture);
            Image = imgDataURL;

            var plantpicture = await _context.PlantPictures.FirstOrDefaultAsync(m => m.PlantPictureId == id);
            if (plantpicture == null)
            {
                return NotFound();
            }
            PlantPicture = plantpicture;
            ViewData["PlantId"] = new SelectList(_context.Plants, "PlantId", "PlantName");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            //if (!ModelState.IsValid)
            //{
            //    return Page();
            //}

            _context.Attach(PlantPicture).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlantPictureExists(PlantPicture.PlantPictureId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PlantPictureExists(int id)
        {
            return (_context.PlantPictures?.Any(e => e.PlantPictureId == id)).GetValueOrDefault();
        }

        public string RenderImage(int id)
        {
            byte[] picture = _context.PlantPictures.Find(id).Picture;
            //Image = File(picture, "image/jpeg");

            string imreBase64Data = Convert.ToBase64String(picture);
            string imgDataURL = string.Format("data:image/jpeg;base64,{0}", imreBase64Data);

            var image = imgDataURL;

            return image;
        }
    }
}

PlantBuddy/Pages/Plants/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Plants
{
    public class CreateModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public CreateModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Plant Plant { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Plant == null || Plant == null)
            {
                return Page();
            }

            _context.Plant.Add(Plant);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PlantBuddy/Pages/Plants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Plants
{
    public class DeleteModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public DeleteModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        [BindProperty]
      public Plant Plant { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Plant == null)
            {
                return NotFound();
            }

            var plant = await _context.Plant.FirstOrDefaultAsync(m => m.PlantId == id);

            if (plant == null)
            {
                return NotFound();
            }
            else 
            {
                Plant = plant;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.Plant == null)
            {
                return NotFound();
            }
            var plant = await _context.Plant.FindAsync(id);

            if (plant != null)
            {
                Plant = plant;
                _context.Plant.Remove(Plant);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

PlantBuddy/Pages/Plants/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Plants
{
    public class DetailsModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public DetailsModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        [BindProperty] public Plant Plant { get; set; } = default!;
        [BindProperty] public DateTime DateWatered { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Plants == null)
            {
                return NotFound();
            }

            var plant = await _context.Plants.FirstOrDefaultAsync(m => m.PlantId == id);
            if (plant == null)
            {
                return NotFound();
            }
            else 
            {
                Plant = plant;
            }

            DateWatered = DateTime.Now;

            return Page();
        }

        public async Task<IActionResult> OnPostAddWaterHistory(int id)
        {
            var waterHistory = new WaterHistory()
            {
                CreatedDate = DateTime.Now,
                LastModifiedDate = DateTime.Now,
                PlantId = id,
                WateredOn = DateWatered
            };

            _context.WaterHistories.Add(waterHistory);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Details", new { id = id });
        }
    }
}

PlantBuddy/Pages/Plants/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Plants
{
    public class EditModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public EditModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Plant Plant { get; set; } = default!;

        public List<string> PlantImages { get; set; } = new List<string>();

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Plants == null)
            {
                return NotFound();
            }

            var plant =  await _context.Plants.Include(x => x.Pictures).FirstOrDefaultAsync(m => m.PlantId == id);
            if (plant == null)
            {
                return NotFound();
            }
            Plant = plant;

            foreach (var image in plant.Pictures)
            {
                PlantImages.Add(PlantPicture.ConvertImage(image.Picture));
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Plant).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!PlantExists(Plant.PlantId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool PlantExists(int id)
        {
          return (_context.Plants?.Any(e => e.PlantId == id)).GetValueOrDefault();
        }
    }
}

PlantBuddy/Pages/Plants/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Plants
{
    public class IndexModel : PageModel
    {
        private readonly PlantBuddyContext _context;

        public IndexModel(PlantBuddyContext context)
        {
            _context = context;
        }

        public IList<Plant> Plant { get;set; } = default!;

        public async Task OnGetAsync()
        {
            if (_context.Plant != null)
            {
                Plant = await _context.Plant.ToListAsync();
            }
        }
    }
}

PlantBuddy/Pages/Stores/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Stores
{
    public class CreateModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public CreateModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Store Store { get; set; } = default!;
        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
          if (!ModelState.IsValid || _context.Stores == null || Store == null)
            {
                return Page();
            }

            _context.Stores.Add(Store);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

PlantBuddy/Pages/Stores/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using PlantBuddy.Data;
using PlantBuddy.Models;

namespace PlantBuddy.Pages.Stores
{
    public class DetailsModel : PageModel
    {
        private readonly PlantBuddy.Data.PlantBuddyContext _context;

        public DetailsModel(PlantBuddy.Data.PlantBuddyContext context)
        {
            _context = context;
        }

      public Store Store { get; set; } = default!; 

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.Stores == null)
            {
                return NotFound();
            }

            var store = await _context.Stores.FirstOrDefaultAsync(m => m.StoreId == id);
            if (store == null)
            {
                return NotFound();
            }
            else 
            {
                Store = store;
            }
            return Page();
        }
    }
}

PlantBuddy/Pages/Plants/Create.cshtml
@page
@model PlantBuddy.Pages.Plants.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Plant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Plant.PlantName" class="control-label"></label>
                <input asp-for="Plant.PlantName" class="form-control" />
                <span asp-validation-for="Plant.PlantName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.LightPreference" class="control-label"></label>
                <input asp-for="Plant.LightPreference" class="form-control" />
                <span asp-validation-for="Plant.LightPreference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.ResourceLink" class="control-label"></label>
                <input type="url" asp-for="Plant.ResourceLink" class="form-control" />
                <span asp-validation-for="Plant.ResourceLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.CreatedDate" class="control-label"></label>
                <input asp-for="Plant.CreatedDate" class="form-control" />
                <span asp-validation-for="Plant.CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.LastModifiedDate" class="control-label"></label>
                <input asp-for="Plant.LastModifiedDate" class="form-control" />
                <span asp-validation-for="Plant.LastModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.StoreId" class="control-label"></label>
                <select asp-for="Plant.StoreId" class="form-control" asp-items="ViewBag.StoreId"></select>
                <span asp-validation-for="Plant.StoreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PlantBuddy/Pages/Plants/Delete.cshtml
@page
@model PlantBuddy.Pages.Plants.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Plant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.PlantName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.PlantName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.LightPreference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.LightPreference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.LastModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.LastModifiedDate)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Plant.PlantId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

PlantBuddy/Pages/Plants/Details.cshtml
@page
@model PlantBuddy.Pages.Plants.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Plant</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.PlantName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.PlantName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.LightPreference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.LightPreference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.ResourceLink)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.ResourceLink)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.CreatedDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Plant.LastModifiedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Plant.LastModifiedDate)
        </dd>
        <dt class="col-sm-2">
            Add Datetime:
        </dt>
        <dd class="col-sm-10">
            <form asp-page-handler="AddWaterHistory" asp-route-id="@Model.Plant.PlantId" method="post">
                <div class="input-group mb-3">
                    <input class="form-control" asp-for="@Model.DateWatered" />
                    <button class="btn btn-default">Add</button>
                </div>
            </form>
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Plant?.PlantId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

<!-- Load d3.js -->
<script src="https://d3js.org/d3.v4.js"></script>

<!-- Create a div where the graph will take place -->
<div id="my_dataviz"></div>

<script>

    // set the dimensions and margins of the graph
    var margin = { top: 10, right: 30, bottom: 90, left: 40 },
        width = 460 - margin.left - margin.right,
        height = 500 - margin.top - margin.bottom;

    // append the svg object to the body of the page
    var svg = d3.select("#my_dataviz")
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform",
            "translate(" + margin.left + "," + margin.top + ")");

    // Parse the Data
    d3.json("https://localhost:7290/waterhistory/details/3", function (data) {
    //d3.csv("https://raw.githubusercontent.com/holtzy/data_to_viz/master/Example_dataset/7_OneCatOneNum_header.csv", function (data) {
        console.log(data);

        // X axis
        var x = d3.scaleTime()
            .domain(d3.extent(data, function (d) { return d3.timeParse("%Y-%m-%d")(d.date); }))
            .range([0, width]);
        svg.append("g")
            .attr("transform", "translate(0," + height + ")")
            .call(d3.axisBottom(x));

        // Add Y axis
        var y = d3.scaleLinear()
            .domain([0, 1])
            .range([height, 0]);
        svg.append("g")
            .call(d3.axisLeft(y));

        // Lines
        svg.selectAll("myline")
            .data(data)
            .enter()
            .append("line")
            .attr("x1", function (d) { return x(d3.timeParse("%Y-%m-%d")(d.date)); })
            .attr("x2", function (d) { return x(d3.timeParse("%Y-%m-%d")(d.date)); })
            .attr("y1", function (d) { return y(d.value); })
            .attr("y2", y(0))
            .attr("stroke", "grey")

        // Circles
        svg.selectAll("mycircle")
            .data(data)
            .enter()
            .append("circle")
            .attr("cx", function (d) { return x(d3.timeParse("%Y-%m-%d")(d.date)); })
            .attr("cy", function (d) { return y(d.value); })
            .attr("r", "4")
            .style("fill", "#69b3a2")
            .attr("stroke", "black")
    })

</script>

PlantBuddy/Pages/Plants/Edit.cshtml
@page
@model PlantBuddy.Pages.Plants.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Plant</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Plant.PlantId" />
            <div class="form-group">
                <label asp-for="Plant.PlantName" class="control-label"></label>
                <input asp-for="Plant.PlantName" class="form-control" />
                <span asp-validation-for="Plant.PlantName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.LightPreference" class="control-label"></label>
                <input asp-for="Plant.LightPreference" class="form-control" />
                <span asp-validation-for="Plant.LightPreference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.ResourceLink" class="control-label"></label>
                <input type="url" asp-for="Plant.ResourceLink" class="form-control" />
                <span asp-validation-for="Plant.ResourceLink" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.CreatedDate" class="control-label"></label>
                <input asp-for="Plant.CreatedDate" class="form-control" />
                <span asp-validation-for="Plant.CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Plant.LastModifiedDate" class="control-label"></label>
                <input asp-for="Plant.LastModifiedDate" class="form-control" />
                <span asp-validation-for="Plant.LastModifiedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col">
        @foreach (var picture in Model.PlantImages)
        {
            <img height="200" src="@picture" />
        }
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PlantBuddy/Pages/Plants/Index.cshtml
@page
@model PlantBuddy.Pages.Plants.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Plant[0].PlantName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plant[0].LightPreference)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plant[0].CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Plant[0].LastModifiedDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Plant) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.PlantName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LightPreference)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastModifiedDate)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.PlantId">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.PlantId">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.PlantId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>